apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerized-agents
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerized-agents
  template:
    metadata:
      labels:
        app: dockerized-agents
    spec:
      containers:
      - name: football-agent
        image: brettmulder/football-agent
        ports:
        - containerPort: 5000
      - name: music-agent
        image: brettmulder/music-agent
        ports:
          - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
   name: dockerized-agents-entrypoint
   namespace: default
spec:
   type: NodePort
   selector:
      app: dockerized-agents
   ports:
      - port: 3000
        targetPort: 3000
        nodePort: 30001